UT changes
akgunjal/block-storage-attacher pull request #1
Opened 2018-07-26 10:24 UTC by mumutyal

2018-07-26 11:07 UTC, akgunjal requested changes

2018-07-26 11:07 UTC, akgunjal commented on watcher/pv_watcher_test.go
> +	Validate(pv)
Add assertion to this test.

2018-07-27 07:34 UTC, mumutyal commented on watcher/pv_watcher_test.go
> +	Validate(pv)
Added assertion to validate function

2018-07-27 08:16 UTC, akgunjal approved these changes

2018-07-27 08:16 UTC, merged