Jenkins e2e changes
akgunjal/block-storage-attacher pull request #5
Opened 2018-09-18 12:11 UTC by mumutyal

2018-09-19 08:03 UTC, akgunjal requested changes

2018-09-19 08:03 UTC, akgunjal commented on tests/e2e/e2e-tests/block_volume_attach.go
> +                        cmd.Env = append(cmd.Env, "SL_USERNAME=1186049_contdep@us.ibm.com")
Why are the credentials hard coded? Is it similar in other e2e tests also?

2018-09-19 08:03 UTC, akgunjal commented on tests/e2e/e2e-tests/block_volume_attach.go
> +                                if strings.Contains(outStr, "/") {
why is there 2 types of PV names? Paste the different types of PV name you expect since you added `if/else` condition for parsing names.

2018-09-19 08:03 UTC, akgunjal commented on tests/e2e/e2e-tests/block_volume_attach.go
> +                                fmt.Printf("Annotaitons :\n%s\n", pv.ObjectMeta.Annotations["ibm.io/attachstatus"])
Typo in `Annotaitons`.
Also you need to print device path rather than`iqn` I think.

2018-09-19 08:03 UTC, akgunjal commented on tests/e2e/e2e-tests/block_volume_attach.go
> +				//attachStatus, err := getAttchStatus()
I see the getAttachStatus() call is commented. You need to check the status and device path and assert based on that. Why is that code removed?

2018-09-19 08:03 UTC, akgunjal commented on tests/e2e/e2e-tests/block_volume_attach.go
> +	for start := time.Now(); time.Since(start) < (5 * time.Minute); {
You need to wait for 10mins as I said. Revert it back to 10mins unless you have a different reason to wait only for 5mins.

2018-09-19 08:03 UTC, akgunjal commented on tests/e2e/e2e.sh
> +# Build Latest plugin images (if configured), otherwise use the existing one specified in conf
Remove these commented code if not needed.

2018-09-19 08:03 UTC, akgunjal commented on tests/e2e/e2e.sh
> +if [[ $TEST_CODE_BUILD == "true" ]]; then
Can you explain which binary are you building? I also see the cert file names are hardcoded.

2018-09-19 09:30 UTC, mumutyal commented on tests/e2e/e2e-tests/block_volume_attach.go
> +                                if strings.Contains(outStr, "/") {
We will get one these two outputs thats y added if else

2018-09-19 09:48 UTC, mumutyal commented on tests/e2e/e2e-tests/block_volume_attach.go
> +                                fmt.Printf("Annotaitons :\n%s\n", pv.ObjectMeta.Annotations["ibm.io/attachstatus"])
got it

2018-09-19 09:51 UTC, mumutyal commented on tests/e2e/e2e-tests/block_volume_attach.go
> +				//attachStatus, err := getAttchStatus()
Attach stauts is coming blank and fialing on timeout to check other functionality commented once that is fixed wil add

2018-09-19 09:56 UTC, mumutyal commented on tests/e2e/e2e.sh
> +if [[ $TEST_CODE_BUILD == "true" ]]; then
we are not building any binary just to run the e2e testcases

2018-09-19 10:00 UTC, mumutyal commented on tests/e2e/e2e.sh
> +# Build Latest plugin images (if configured), otherwise use the existing one specified in conf
Removed

2018-09-24 07:31 UTC, akgunjal approved these changes

2018-09-24 07:31 UTC, merged